# @name get-prompts
GET http://localhost:3333/prompts

###
# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="daarui.mp3"
Content-Type: image/png

< ./daarui.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/18f57a14-edae-4b32-a1a4-22a297bf5049/transcription
Content-Type: application/json

{
  "prompt": "marinha, kuma, roronoa zoro, companheira, nakama, one piece, mugiwaras, chapéus de palha, bando, três espadas, Mihawk, gran line, vivy, ussop,bando, wano, oden, ambição, haki do rei, sandai kitetsu, wado ichimonji, shisui, doflamingo, Orochi, Kaidou, Enma"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "18f57a14-edae-4b32-a1a4-22a297bf5049",
  "temperature": 0.5,
  "prompt": "create a simple resume of this video transcription: '''{transcription}'''"
}